# For reference http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
- 2.11.8
- 2.12.1
script: sbt clean test
dist: trusty
jdk:
- oraclejdk8
- openjdk8
notifications:
  email:
    recipients:
    - valentin@willscher.de